<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<PropertyGroup>
		<WinUIToolkitPlatform Condition="'$(Platform)' == 'Win32'">x86</WinUIToolkitPlatform>
		<WinUIToolkitPlatform Condition="'$(Platform)' != 'Win32'">$(Platform)</WinUIToolkitPlatform>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="$(MSBuildThisFileDirectory)..\..\lib\native\XamlToolkit.WinUI.Rive.winmd">
			<Implementation>XamlToolkit.WinUI.Rive.dll</Implementation>
		</Reference>
		<ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)..\..\runtimes\win-$(WinUIToolkitPlatform)\native\XamlToolkit.WinUI.Rive.dll" />
		<SDKReference Include="Microsoft.VCLibs.Desktop, Version=14.0" />
	</ItemGroup>

</Project>