import "StateMachineInputCollection.idl";

namespace XamlToolkit.WinUI.Rive
{
    [contentproperty("StateMachineInputCollection")]
    runtimeclass RivePlayer : Microsoft.UI.Xaml.Controls.Control
    {
        RivePlayer();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty SourceProperty{ get; };
        String Source;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ArtboardProperty{ get; };
        String Artboard;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty StateMachineProperty{ get; };
        String StateMachine;

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty StateMachineInputCollectionProperty{ get; };
        StateMachineInputCollection StateMachineInputCollection;

        void SetBool(String name, Boolean value);

        void SetNumber(String name, Single value);

        void FireTrigger(String name);
    }
}
