namespace XamlToolkit.WinUI.Rive
{
    unsealed runtimeclass StateMachineInput : Microsoft.UI.Xaml.DependencyObject
    {
        StateMachineInput();

        String Target;
    }

    [contentproperty("Value")]
    runtimeclass BoolInput : StateMachineInput
    {
        BoolInput();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

        Windows.Foundation.IReference<Boolean> Value;
    }

    [contentproperty("Value")]
    runtimeclass NumberInput : StateMachineInput
    {
        NumberInput();

        [noexcept]
        static Microsoft.UI.Xaml.DependencyProperty ValueProperty{ get; };

        Windows.Foundation.IReference<Double> Value;
    }

    runtimeclass TriggerInput : StateMachineInput
    {
        TriggerInput();

        void Fire();
    }
}
